export const red_skill = [
  {
    rune_name_en: "shout_of_terror",
    rune_name_ch: "恐怖的吶喊",
    rune_content:
      "對施展者周圍範圍內的敵人造成傷害後，使防禦度減幅。以一定的機率對受到傷害的敵人造成暈眩",
    rune_img_url: "/img/rune/skill/red/恐怖的吶喊.jpg",
    link_url: "/rune/shout_of_terror",
    rune_tag: [
      "攻擊",
      "近距",
      "廣域",
      "吶喊",
      "打擊",
      "物理",
      "持續時間",
      "恐怖的吶喊",
    ],
    rune_limit: ["無連結限制", "可使用所有武器"],
    rune_rank_effect: {
      magic: "恐怖吶喊的防禦度抵抗效果+10%",
      rare: "恐怖吶喊的防禦度抵抗效果+24%",
      legend: "恐怖吶喊的防禦度抵抗效果+40%",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "frost_wave",
    rune_name_ch: "寒霜波動",
    rune_content: "向前方釋放冰霜，對敵人造成傷害",
    rune_img_url: "/img/rune/skill/red/寒霜波動.jpg",
    link_url: "/rune/frost_wave",
    rune_tag: ["攻擊", "近距", "廣域", "打擊", "冰霜", "寒霜波動"],
    rune_limit: ["無連結限制", "可使用劍、斧頭、鈍器及手杖"],
    rune_rank_effect: {
      magic: "惡寒機率+10%<br>惡寒效果+15%",
      rare: "惡寒機率+15%<br>惡寒效果+30%<br>對處於冰霜狀態異常的敵人傷害增幅15%<br>廣域範圍+50",
      legend:
        "惡寒機率+20%<br>惡寒效果+45%<br>對處於冰霜狀態異常的敵人傷害增幅30%<br>廣域範圍+100",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "shield_charge",
    rune_name_ch: "盾牌突擊",
    rune_content: "向前方突進，對敵人造成物理傷害",
    rune_img_url: "/img/rune/skill/red/盾牌突擊.jpg",
    link_url: "/rune/shield_charge",
    rune_tag: ["攻擊", "近距", "廣域", "打擊", "物理", "移動", "盾牌突擊"],
    rune_limit: ["無連結限制", "可使用盾牌"],
    rune_rank_effect: {
      magic: "防禦度貫穿+10%<br>攻擊命中度+20%",
      rare: "防禦度貫穿+10%<br>攻擊命中度+20%<br>技能命中射程距離最遠的敵人時，暈眩發生指數+50<br>打擊倍率+80%",
      legend:
        "防禦度貫穿+15%<br>攻擊命中度+30%<br>技能命中射程距離最遠的敵人時，暈眩發生指數+500<br>打擊倍率+170%",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "combo",
    rune_name_ch: "連擊",
    rune_content: "揮動武器攻擊敵人2次，命中時，將因狂奔效果，加速造成傷害",
    rune_img_url: "/img/rune/skill/red/連擊.jpg",
    link_url: "/rune/combo",
    rune_tag: ["攻擊", "近距", "武器範圍", "打擊", "物理", "連擊"],
    rune_limit: ["無連結限制", "可使用劍及斧頭"],
    rune_rank_effect: {
      magic: "狂奔效果+50%<br>武器範圍+5<br>打擊傷害倍率+15%<br>防禦貫穿度+5%",
      rare: "狂奔效果+75%<br>武器範圍+25<br>打擊傷害倍率+30%<br>防禦貫穿度+10%",
      legend:
        "狂奔效果+100%<br>武器範圍+50<br>打擊傷害倍率+60%<br>防禦貫穿度+15%",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "illusion_axe",
    rune_name_ch: "幻影斧頭",
    rune_content: "在施展者附近召喚旋轉的幻影斧頭，對敵人造成傷害",
    rune_img_url: "/img/rune/skill/red/幻影斧頭.jpg",
    link_url: "/rune/illusion_axe",
    rune_tag: [
      "攻擊",
      "近距",
      "廣域",
      "打擊",
      "物理",
      "切換",
      "傷害切換",
      "幻影斧頭",
    ],
    rune_limit: ["無連結限制", "可使用所有武器"],
    rune_rank_effect: {
      magic: "廣域範圍+25",
      rare: "廣域範圍+50",
      legend: "廣域範圍+100",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "lightning_strike",
    rune_name_ch: "閃電打擊",
    rune_content: "在前方與施展者附近降下閃電，對敵人造成傷害",
    rune_img_url: "/img/rune/skill/red/閃電打擊.jpg",
    link_url: "/rune/lightning_strike",
    rune_tag: ["攻擊", "廣域", "打擊", "閃電", "投射體", "合成限定", "閃電打擊"],
    rune_limit: ["無法並列發射，無法分離，無法連鎖", "可使用斧頭、鈍器及手杖"],
    rune_rank_effect: {
      magic: "觸電機率+5%<br>對處於觸電狀態的敵人傷害10%增幅",
      rare: "觸電機率+8%<br>對處於觸電狀態的敵人傷害15%增幅<br>爆炸範圍+50",
      legend:
        "觸電機率+10%<br>對處於觸電狀態的敵人傷害30%增幅<br>爆炸範圍+50<br>投射體數量+1",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "explosive_slash",
    rune_name_ch: "爆炸斬擊",
    rune_content:
      "命中時，賦予敵人弱化效果，並於擊殺處於弱化效果敵人時爆炸，對周圍造成傷害",
    rune_img_url: "/img/rune/skill/red/爆炸斬擊.jpg",
    link_url: "/rune/explosive_slash",
    rune_tag: ["攻擊", "近距", "廣域", "武器範圍", "打擊", "火焰", "爆炸斬擊"],
    rune_limit: ["無連結限制", "可使用劍及斧頭"],
    rune_rank_effect: {
      magic: "廣域範圍+10%<br>廣域傷害10%增幅",
      rare: "廣域範圍+25%<br>廣域傷害15%增幅<br>火焰貫穿+15%",
      legend: "廣域範圍+40%<br>廣域傷害30%增幅<br>火焰貫穿+30%",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "earth_blow",
    rune_name_ch: "地面強擊",
    rune_content:
      "強擊地面，對敵人造成傷害。使用技能時，獲得腕力效果，移動時將效果解除",
    rune_img_url: "/img/rune/skill/red/地面強擊.jpg",
    link_url: "/rune/earth_blow",
    rune_tag: ["攻擊", "近距", "廣域", "打擊", "物理", "強擊", "地面強擊"],
    rune_limit: ["無連結限制", "可使用斧頭、鈍器及手杖"],
    rune_rank_effect: {
      magic: "腕力效果+20%<br>攻擊暴擊度+20%<br>攻擊暴擊傷害+20%",
      rare: "腕力效果+40%<br>攻擊暴擊度+40%<br>攻擊暴擊傷害+30%<br>傷害10%增幅",
      legend:
        "腕力效果+60%<br>攻擊暴擊度+60%<br>攻擊暴擊傷害+40%<br>傷害20%增幅",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "leap_attack",
    rune_name_ch: "飛躍攻擊",
    rune_content: "向前方飛躍，落地時，對敵人造成傷害並擊退敵人",
    rune_img_url: "/img/rune/skill/red/飛躍攻擊.jpg",
    link_url: "/rune/leap_attack",
    rune_tag: ["攻擊", "近距", "廣域", "打擊", "物理", "移動", "飛躍攻擊"],
    rune_limit: ["無連結限制", "可使用短劍、劍、斧頭、鈍器及手杖"],
    rune_rank_effect: {
      magic: "擊退距離+20%<br>擊退距離+10%",
      rare: "擊退距離+35%<br>擊退距離+20%<br>廣域範圍+30",
      legend: "擊退距離+50%<br>擊退距離+30%<br>廣域範圍+60",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "whirlwind",
    rune_name_ch: "旋風",
    rune_content: "維持集中時，朝操作方向迴轉並移動，對周圍敵人造成傷害",
    rune_img_url: "/img/rune/skill/red/旋風.jpg",
    link_url: "/rune/whirlwind",
    rune_tag: ["攻擊", "近距", "武器範圍", "集中", "打擊", "物理", "旋風"],
    rune_limit: ["無連結限制", "可使用短劍、劍、斧頭、鈍器及手杖"],
    rune_rank_effect: {
      magic: "武器範圍+30<br>移動速度減幅30%<br>近距離傷害+50%",
      rare: "武器範圍+60<br>移動速度減幅25%<br>近距離傷害+100%",
      legend:
        "武器範圍+100<br>移動速度減幅15%<br>近距離傷害+200%<br>攻擊速度3%增幅",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "crescent_slash",
    rune_name_ch: "半月斬擊",
    rune_content: "廣範圍揮擊武器，對多數敵人造成物理傷害",
    rune_img_url: "/img/rune/skill/red/半月斬擊.jpg",
    link_url: "/rune/crescent_slash",
    rune_tag: ["攻擊", "近距", "武器範圍", "打擊", "物理", "半月斬擊"],
    rune_limit: ["無連結限制", "可使用劍及斧頭"],
    rune_rank_effect: {
      magic: "武器範圍+30<br>近距離傷害+50%",
      rare: "武器範圍+60<br>近距離傷害+100%<br>打擊傷害倍率+100%",
      legend: "武器範圍+120<br>近距離傷害+200%<br>打擊傷害倍率+150%",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "lightning_vortex",
    rune_name_ch: "閃電漩渦",
    rune_content: "向前方飛躍，落地時，對敵人造成傷害並擊退敵人",
    rune_img_url: "/img/rune/skill/red/閃電漩渦.jpg",
    link_url: "/rune/lightning_vortex",
    rune_tag: ["攻擊", "近距", "廣域", "打擊", "閃電", "閃電漩渦"],
    rune_limit: ["無連結限制", "可使用劍、斧頭、鈍器及手杖"],
    rune_rank_effect: {
      magic: "閃電傷害+50%<br>廣域範圍+10%",
      rare: "閃電傷害+100%<br>廣域範圍+20%<br>觸電機率+8%",
      legend: "閃電傷害+150%<br>廣域範圍+30%<br>觸電機率+8%<br>漩渦打擊次數+1",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "illusion_hook",
    rune_name_ch: "幻影鉤",
    rune_content:
      "丟擲鉤子，對敵人造成物理傷害，遭擊中的敵人將被拉至施法者前方",
    rune_img_url: "/img/rune/skill/red/幻影鉤.jpg",
    link_url: "/rune/illusion_hook",
    rune_tag: ["咒文", "近距", "廣域", "打擊", "物理", "幻影鉤"],
    rune_limit: ["無連結限制", "可使用所有武器"],
    rune_rank_effect: {
      magic:
        "技能符文效果+10%<br>廣域範圍+50<br>對處於妨礙行動狀態的敵人傷害+100%",
      rare: "技能符文效果+20%<br>廣域範圍+100<br>技能符文持續時間+1<br>對處於妨礙行動狀態的敵人傷害+150%",
      legend:
        "技能符文效果+60%<br>廣域範圍+150<br>技能符文持續時間+1<br>對處於妨礙行動狀態的敵人傷害+200%",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "shield_strike",
    rune_name_ch: "盾牌打擊",
    rune_content: "以盾牌推擊敵人，造成物理傷害",
    rune_img_url: "/img/rune/skill/red/盾牌打擊.jpg",
    link_url: "/rune/shield_strike",
    rune_tag: ["攻擊", "近距", "廣域", "打擊", "物理", "盾牌打擊"],
    rune_limit: ["無連結限制", "可使用盾牌"],
    rune_rank_effect: {
      magic: "廣域範圍+10%<br>打擊傷害倍率+25%",
      rare: "廣域範圍+20%F<br>打擊傷害倍率+50%<br>防禦度貫穿+10%<br>元素貫穿+10%",
      legend:
        "廣域範圍+40%<br>打擊傷害倍率+100%<br>防禦度貫穿+25%<br>元素貫穿+25%",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "quick_slash",
    rune_name_ch: "迅速斬擊",
    rune_content: "命中單一敵人時，劍流將流向周圍敵人，造成額外傷害",
    rune_img_url: "/img/rune/skill/red/迅速斬擊.jpg",
    link_url: "/rune/quick_slash",
    rune_tag: ["攻擊", "近距", "武器範圍", "打擊", "物理", "迅速斬擊"],
    rune_limit: ["無連結限制", "可使用劍及斧頭"],
    rune_rank_effect: {
      magic: "連鎖次數+1<br>攻擊速度+10%<br>攻擊時，傷害+50%",
      rare: "連鎖次數+2<br>攻擊速度+20%<br>攻擊時，傷害+100%<br>打擊傷害倍率+50%",
      legend:
        "連鎖次數+4<br>攻擊速度+30%<br>攻擊時，傷害+150%<br>打擊傷害倍率+100%",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "Fissure",
    rune_name_ch: "地面裂縫",
    rune_content:
      "對施展者周圍範圍內的敵人造成傷害後，使防禦度減幅。以一定的機率對受到傷害的敵人造成暈眩。",
    rune_img_url: "/img/rune/skill/red/地面裂縫.jpg",
    link_url: "/rune/Fissure",
    rune_tag: ["攻擊", "近距", "廣域", "打擊", "物理", "地面裂縫"],
    rune_limit: ["無連結限制", "可使用斧頭、鈍器及手杖"],
    rune_rank_effect: {
      magic: "與敵人的距離在400以下時，傷害倍率+40%<br>廣域範圍+30",
      rare: "與敵人的距離在400以下時，傷害倍率+80%<br>廣域範圍+60<br>廣域傷害+50%",
      legend:
        "與敵人的距離在400以下時，傷害倍率+120%<br>廣域範圍+90<br>廣域傷害+100%",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "bloodshed",
    rune_name_ch: "血擊",
    rune_content: "對命中的目標造成出血傷害，且形成血之領域",
    rune_img_url: "/img/rune/skill/red/血擊.jpg",
    link_url: "/rune/bloodshed",
    rune_tag: ["攻擊", "近距", "廣域", "武器範圍", "打擊", "物理", "血擊"],
    rune_limit: ["無連結限制", "可使用劍及斧頭"],
    rune_rank_effect: {
      magic:
        "對精銳傷害+30%<br>血擊血域效果+15%<br>對處於出血狀態的敵人傷害5%增幅",
      rare: "對精銳傷害+50%<br>血擊血域效果+30%<br>出血機率+5%<br>對處於出血狀態的敵人傷害5%增幅",
      legend:
        "對精銳傷害+100%<br>血擊血域效果+50%<br>出血機率+10%<br>對處於出血狀態的敵人傷害20%增幅",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "frost_strike",
    rune_name_ch: "寒霜強擊",
    rune_content: "使強擊地面的位置上竄出寒霜柱，對敵人造成傷害",
    rune_img_url: "/img/rune/skill/red/寒霜強擊.jpg",
    link_url: "/rune/frost_strike",
    rune_tag: ["攻擊", "近距", "廣域", "打擊", "冰霜", "強擊", "寒霜強擊"],
    rune_limit: ["無連結限制", "可使用斧頭、鈍器及手杖"],
    rune_rank_effect: {
      magic:
        "冰凍發生指數+5<br>對處於冰霜狀態異常的敵人傷害增幅10%<br>冰霜貫穿+5%",
      rare: "冰凍發生指數+10<br>對處於冰霜狀態異常的敵人傷害增幅20%<br>冰霜貫穿+10%<br>廣域範圍+25",
      legend:
        "冰凍發生指數+15<br>對處於冰霜狀態異常的敵人傷害增幅30%<br>冰霜貫穿+15%<br>廣域範圍+50",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "fighter's_wrath",
    rune_name_ch: "鬥士的憤怒",
    rune_content: "在持續時間內，近距離傷害增幅，攻擊速度增加",
    rune_img_url: "/img/rune/skill/red/鬥士的憤怒.jpg",
    link_url: "/rune/fighter's_wrath",
    rune_tag: ["咒文", "攻擊強化", "持續時間", "鬥士的憤怒"],
    rune_limit: ["無連結限制", "可使用所有武器"],
    rune_rank_effect: {
      magic: "強化技能符文效果+5%",
      rare: "強化技能符文效果+10%",
      legend: "強化技能符文效果+15%",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "bulwark_of_protection",
    rune_name_ch: "守護屏障",
    rune_content: "在持續時間內，防禦度及元素抵抗力增加",
    rune_img_url: "/img/rune/skill/red/守護屏障.jpg",
    link_url: "/rune/bloodshed",
    rune_tag: ["咒文", "防禦強化", "持續時間", "守護屏障"],
    rune_limit: ["無連結限制", "可使用所有武器"],
    rune_rank_effect: {
      magic: "強化技能符文效果+6%",
      rare: "強化技能符文效果+15%",
      legend: "強化技能符文效果+25%",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "shout_of_provocation",
    rune_name_ch: "挑釁的吶喊",
    rune_content:
      "持續時間內，增加施展者的防禦，並使範圍內的敵人攻擊施展者。使用時短時間內傷害量增加",
    rune_img_url: "/img/rune/skill/red/挑釁的吶喊.jpg",
    link_url: "/rune/shout_of_provocation",
    rune_tag: ["攻擊", "廣域", "吶喊", "持續時間", "挑釁的吶喊"],
    rune_limit: ["無連結限制", "可使用所有武器"],
    rune_rank_effect: {
      magic: "吶喊技能符文效果+5%",
      rare: "吶喊技能符文效果+12%",
      legend: "吶喊技能符文效果+20%",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "blood_explosion",
    rune_name_ch: "血之爆炸",
    rune_content: "引發出血達到疊加層數時，以一定的機率對周圍引發血之爆炸",
    rune_img_url: "/img/rune/skill/red/血之爆炸.jpg",
    link_url: "/rune/blood_explosion",
    rune_tag: [
      "攻擊",
      "近距",
      "廣域",
      "打擊",
      "物理",
      "持續時間",
      "切換",
      "傷害切換",
      "血之爆炸",
    ],
    rune_limit: ["無連結限制", "可使用劍及斧頭"],
    rune_rank_effect: {
      magic: "廣域範圍+25",
      rare: "廣域範圍+50<br>對處於出血狀態的敵人傷害+50%",
      legend: "廣域範圍+80<br>對處於出血狀態的敵人傷害+100%",
    },
    sub_content: [],
    source: [],
  },

  {
    rune_name_en: "guardian",
    rune_name_ch: "守護者",
    rune_content:
      "對施展者周圍的敵人造成物理傷害，使被打擊的目標引發暈眩或鈍化",
    rune_img_url: "/img/rune/skill/red/守護者.jpg",
    link_url: "/rune/guardian",
    rune_tag: ["攻擊", "近距", "廣域", "打擊", "物理", "持續時間", "守護者"],
    rune_limit: ["無連結限制", "可使用盾牌"],
    rune_rank_effect: {
      magic: "強化技能符文效果+100%",
      rare: "強化技能符文效果+200%",
      legend: "強化技能符文效果+300%<br>技能符文持續時間+1",
    },
    rune_lv30: {
      consume: "34.4",
      value: "物理傷害+248<br>物理傷害651%<br>暈眩發生指數+55",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "bloodshed",
    rune_name_ch: "忍受的痛苦",
    rune_content:
      "使用技能時，根據疊加數，防禦度上升，達疊加上限時獲得強化增益效果",
    rune_img_url: "/img/rune/skill/red/忍受的痛苦.jpg",
    link_url: "/rune/bloodshed",
    rune_tag: ["咒文", "防禦強化", "切換", "效果切換", "忍受的痛苦"],
    rune_limit: ["無連結限制", "可使用所有武器"],
    rune_rank_effect: {
      magic: "強化技能符文效果+100%",
      rare: "強化技能符文效果+200%",
      legend: "強化技能符文效果+300%<br>技能符文持續時間+1",
    },
    rune_lv30: {
      consume: "15%",
      value: "每個疊加防禦度+7",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "whirlwind_slash",
    rune_name_ch: "迴旋斬擊",
    rune_content: "尖銳地刺傷四周，造成對象持續性的傷害",
    rune_img_url: "/img/rune/skill/red/迴旋斬擊.jpg",
    link_url: "/rune/whirlwind_slash",
    rune_tag: ["攻擊", "近距", "攻擊範圍", "持續傷害", "物理", "迴旋斬擊"],
    rune_limit: ["無連結限制", "可使用劍及斧頭"],
    rune_rank_effect: {
      magic: "持續傷害40%<br>武器範圍+20",
      rare: "持續傷害80%<br>武器範圍+40",
      legend: "持續傷害80%<br>武器範圍+60<br>持續傷害7%增幅",
    },
    rune_lv30: {
      consume: "13.7",
      value: "物理持續傷害+222<br>物理持續傷害591%",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "tenacious_regeneration",
    rune_name_ch: "堅毅的復甦力",
    rune_content: "在持續時間內，增加生命力與生命力復甦",
    rune_img_url: "/img/rune/skill/red/堅毅的復甦力.jpg",
    link_url: "/rune/tenacious_regeneration",
    rune_tag: ["咒文", "防禦強化", "持續時間", "合成限定", "堅毅的復甦力"],
    rune_limit: ["無連結限制", "可使用所有武器"],
    rune_rank_effect: {
      magic: "強化技能符文效果+5%",
      rare: "強化技能符文效果+12%",
      legend: "強化技能符文效果+20%",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "seal_of_condensed_destruction",
    rune_name_ch: "凝聚破壞紋章",
    rune_content: "增加目標的物理傷害",
    rune_img_url: "/img/rune/skill/red/凝聚破壞紋章.jpg",
    link_url: "/rune/seal_of_condensed_destruction",
    rune_tag: ["咒文", "攻擊紋章", "切換", "合成限定", "凝聚破壞紋章"],
    rune_limit: ["無連結限制", "可使用所有武器"],
    rune_rank_effect: {
      magic: "N/A",
      rare: "光環及紋章效果+30%",
      legend: "光環及紋章效果+60%",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "seal_of_defense",
    rune_name_ch: "防禦紋章",
    rune_content: "使目標的防禦度增加",
    rune_img_url: "/img/rune/skill/red/防禦紋章.jpg",
    link_url: "/rune/seal_of_defense",
    rune_tag: ["咒文", "防禦紋章", "切換", "公會限定", "防禦紋章"],
    rune_limit: ["無連結限制", "可使用所有武器"],
    rune_rank_effect: {
      magic: "N/A",
      rare: "光環及紋章效果+30%",
      legend: "光環及紋章效果+60%",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "seal_of_crowd_control_dodge",
    rune_name_ch: "控制狀態異常迴避紋章",
    rune_content: "增加目標的控制狀態異常迴避率",
    rune_img_url: "/img/rune/skill/red/控制狀態異常迴避紋章.jpg",
    link_url: "/rune/seal_of_crowd_control_dodge",
    rune_tag: ["咒文", "防禦紋章", "切換", "公會限定", "控制狀態異常迴避紋章"],
    rune_limit: ["無連結限制", "可使用所有武器"],
    rune_rank_effect: {
      magic: "N/A",
      rare: "光環及紋章效果+40%",
      legend: "光環及紋章效果+70%",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "shout_of_justice",
    rune_name_ch: "正義的吶喊",
    rune_content:
      "持續時間內，使範圍內敵人移動速度減幅並暫時回復體力、解除狀態異常",
    rune_img_url: "/img/rune/skill/red/正義的吶喊.jpg",
    link_url: "/rune/shout_of_justice",
    rune_tag: ["攻擊", "廣域", "吶喊", "持續時間", "合成限定", "正義的吶喊"],
    rune_limit: ["無連結限制", "可使用所有武器"],
    rune_rank_effect: {
      magic: "N/A",
      rare: "吶喊技能符文效果+24%",
      legend: "吶喊技能符文效果+40%",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "fierce_strike",
    rune_name_ch: "猛烈強擊",
    rune_content:
      "召喚錘子，對多數敵人造成物理傷害，每隔一定時間攻擊時，將召喚出更巨大的錘子，造成大幅傷害",
    rune_img_url: "/img/rune/skill/red/猛烈強擊.jpg",
    link_url: "/rune/fierce_strike",
    rune_tag: ["攻擊", "廣域", "打擊", "物理", "強擊", "合成限定", "猛烈強擊"],
    rune_limit: ["無連結限制", "可使用斧頭、鈍器及手杖"],
    rune_rank_effect: {
      magic: "N/A",
      rare: "廣域範圍+25%<br>廣域傷害+60%<br>廣域傷害10%增幅",
      legend: "廣域範圍+50%<br>廣域傷害+100%<br>廣域傷害30%增幅",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "seal_of_physical_domain",
    rune_name_ch: "物理領域紋章",
    rune_content: "使目標所受物理傷害減少",
    rune_img_url: "/img/rune/skill/red/物理領域紋章.jpg",
    link_url: "/rune/seal_of_physical_domain",
    rune_tag: ["咒文", "防禦紋章", "切換", "公會限定", "物理領域紋章"],
    rune_limit: ["無連結限制", "可使用所有武器"],
    rune_rank_effect: {
      magic: "N/A",
      rare: "N/A",
      legend: "光環及紋章效果+25%",
    },
    sub_content: [],
    source: [],
  },
  {
    rune_name_en: "seal_of_strike",
    rune_name_ch: "打擊紋章",
    rune_content: "使目標的打擊傷害增幅",
    rune_img_url: "/img/rune/skill/red/打擊紋章.jpg",
    link_url: "/rune/seal_of_strike",
    rune_tag: ["咒文", "攻擊紋章", "切換", "合成限定", "打擊紋章"],
    rune_limit: ["無連結限制", "可使用所有武器"],
    rune_rank_effect: {
      magic: "N/A",
      rare: "N/A",
      legend: "光環及紋章效果+25%",
    },
    sub_content: [],
    source: [],
  },

  // end
];
